print("  _                  _ ")
print(" | \       |        / \ ")
print(" |  \      |       /   \ ")
print(" |   \     |      /     \ ")
print(" |    \    |     /       \ ")
print(" |     \   |    /         \ ")
print(" |      \  |   /           \ ")
print("_|       \_|  /             \ ")
